/control/verbose 0
/run/initialize

/vis/open OGL
/vis/verbose errors
/vis/scene/create
/vis/scene/add/volume MCP_plus_body_0 -1 1
/vis/sceneHandler/attach
/vis/ogl/set/transparency true
/vis/viewer/set/background white
/vis/viewer/set/style surface
/vis/viewer/set/hiddenEdge true
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/culling coveredDaughters false
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/set/targetPoint 0 0 20 cm
/vis/viewer/zoomTo 1.4
/vis/viewer/flush
/vis/ogl/export mcp_face_plus_z.svg
