/control/verbose 0
/run/initialize

/vis/open OGL
/vis/verbose errors
/vis/scene/create
/vis/scene/add/volume MCP_minus_body_0 -1 1
/vis/scene/add/volume MCP_minus_body_1 -1 1
/vis/sceneHandler/attach
/vis/ogl/set/transparency true
/vis/viewer/set/background white
/vis/viewer/set/style surface
/vis/viewer/set/hiddenEdge true
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/culling coveredDaughters false
/vis/viewer/set/viewpointThetaPhi 90 180
/vis/viewer/set/targetPoint 0 0 -20.15 cm
/vis/viewer/zoomTo 1.3
/vis/viewer/flush
/vis/ogl/export mcp_minus_z.svg
